# Generated by Django 6.0.6 on 2026-06-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=160)),
                ("sub", models.CharField(blank=True, default="", max_length=160)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fund", models.CharField(max_length=200)),
                ("isin", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=80)),
                ("period", models.CharField(max_length=10)),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("FR", "Français"),
                            ("DE", "Deutsch"),
                            ("IT", "Italiano"),
                            ("ES", "Español"),
                        ],
                        default="EN",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Review", "In Review"),
                            ("Validated", "Validated"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who", models.CharField(max_length=80)),
                ("is_me", models.BooleanField(default=False)),
                ("text", models.TextField()),
                ("created_at", models.CharField(max_length=20)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="reporting.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("note", "note"), ("disclaimer", "disclaimer")],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("author", models.CharField(max_length=80)),
                ("created_at", models.CharField(max_length=20)),
                ("text", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("control_id", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                ("descr", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "pass"), ("warn", "warn"), ("fail", "fail")],
                        default="pass",
                        max_length=10,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("signed_by", models.CharField(blank=True, default="", max_length=80)),
                ("signed_at", models.CharField(blank=True, default="", max_length=20)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
